services:
  scraper:
    image: ${DOCKER_HUB_USERNAME}/vidik-scraper:${DOCKER_IMAGE_TAG:-latest}
    container_name: scraper
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: ${DATABASE_URL}
      PEXELS_API_KEY: ${PEXELS_API_KEY}

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    privileged: true
    ports:
      - "12345:12345"
    volumes:
      - "./config.alloy:/etc/alloy/config.alloy"
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # Required for node_exporter integration (OS metrics)
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    environment:
      GRAFANA_LOKI_URL: ${GRAFANA_LOKI_URL}
      GRAFANA_LOKI_USERNAME: ${GRAFANA_LOKI_USERNAME}
      GRAFANA_CLOUD_API_KEY: ${GRAFANA_CLOUD_API_KEY}
      GRAFANA_PROMETHEUS_URL: ${GRAFANA_PROMETHEUS_URL}
      GRAFANA_PROMETHEUS_USERNAME: ${GRAFANA_PROMETHEUS_USERNAME}
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
